### ISSUE TITLE
storage-selector does not support multi partition 

### ISSUE THREAD

**Issue by JaniSuonpera** [ARMmbed/storage-selector#17]
https://github.com/ARMmbed/storage-selector/blob/master/storage-selector.h#L42 is not working for secondary partition. It uses mount point for primary partition.

Mount point for secondary partition has been defined through https://github.com/ARMmbed/mbed-client-pal/blob/master/Configs/pal_config/palInclude_mbedOS.h#L34

**Comment by marcuschangarm** [comment]
@JaniSuonpera the storage selector is by design only instantiating 1 filesystem and 1 block device. Are you asking for an object factory function?

@bridadan @theotherjimmy

**Comment by bridadan** [comment]
@marcuschangarm is correct in that storage selector is only meant to support one filesystem instantiation.

If you need to support multiple filesystem instances, I'd recommend sticking to just the [`storage_selector()`](https://github.com/ARMmbed/storage-selector#using-the-storage) API and then using that block device when setting up your MBRBlockDevice.

**Comment by JaniSuonpera** [comment]
@marcuschangarm I want that FileSystem* filesystem_selector(BlockDevice* bd) returns Filesystem pointer for correct partition. In fact I am finding functionality 
FileSystem* filesystem_selector(MBRBlockDevice(BlockDevice *bd, int part)).

In multi partition case there are required to use class FATFileSystem https://github.com/ARMmbed/mbed-client-testapp/pull/617/files#diff-716a4b29a016262e50d581989a3aff5cR85

**Comment by JanneKiiskila** [comment]
Yep, no specific filesystem dependency allowed, as the filesystem can change.

**Comment by bridadan** [comment]
I'd like double check I understand what you want to do, I'm having trouble reading through the code you provided.

My understanding is that you need to be able to instantiate two `FileSystem` classes to support multiple partitions. Something like this:

```c++
BlockDevice *bd = storage_selector();

MBRBlockDevice bd_part1(bd, 1);
MBRBlockDevice bd_part2(bd, 2);

FileSystem *fs_part1 = filesystem_selector(&bd_part1, "sd1");
FileSystem* fs_part2 = filesystem_selector(&bd_part2, "sd2");
```

Is this correct?

If that's the case, then this is outside of the scope of this library by design. In order to achieve this, we'd have to dynamically allocate the `FileSystem` objects or do even crazier macro magic and use more config options, both of which we wanted to avoid.

**Comment by bridadan** [comment]
However, if this type of thing is necessary for Mbed Cloud Client, then we may have to rethink the scope of the library!

**Comment by bridadan** [comment]
Ok, after thinking about this for a bit I think we have a way of accomplishing this.

**Comment by teetak01** [comment]
We probably in fact need to instantiate at least three partitions in normal Cloud Client application. Two for Cloud client internal use and at least one for customers own data.
