### ISSUE TITLE
Does not compile with Mbed OS master

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/storage-selector#19]
`[ERROR] Library name 'littlefs' is not unique (defined in '/builds/ws/myapp/myapp/storage-selector/littlefs/mbed_lib.json' and '/builds/ws/myapp/myapp/mbed-os/features/filesystem/littlefs/mbed_lib.json')
`

Broken with this commit: 

https://github.com/ARMmbed/mbed-os/commit/2e1c2a1cdf168dd739e777165b21f6cd0509c188

**Comment by teetak01** [comment]
@marcuschangarm @bridadan

**Comment by teetak01** [comment]
Probably need to delete this away for Mbed OS 5.7. https://github.com/ARMmbed/storage-selector/blob/master/littlefs.lib

**Comment by bridadan** [comment]
@teetak01 Thanks for this heads up, we'll go ahead and remove that
