### ISSUE TITLE
Can storage be mandatory parameter in mbed_lib.json?

### ISSUE THREAD

**Issue by artokin** [ARMmbed/storage-selector#23]
Currently storage is mandatory parameter in `mbed_lib.json`:
```
        "storage": {
            "help": "Options are SD_CARD, SPI_FLASH, DATA_FLASH, INTERNAL_FLASH, and HEAP",
            "required": true
        },
```
My application would like to use storage-selector for one board, and other boards should be left without storage because of limited HW resources. 

What should be set for `storage` option for boards that does not use storage? Having `storage` as mandatory parameter will fail a build if nothing is specified:

`[ERROR] Required parameter 'storage-selector.storage' defined by 'library:storage-selector' doesn't have a value
`

**Comment by marcuschangarm** [comment]
Hi @artokin, could you explain a bit more about your use case please?

I'm curious why you want to use the storage selector on a board without storage?

**Comment by artokin** [comment]
Hi @marcuschangarm , my application is fetching storage-selector by using `storage_selector.lib`. 

- My application then compiles OK for boards (like K64F) that have specified value for `storage-selector.storage`.  

- For boards with limited resources I don't want to use storage-selector. But as the storage-selector is fetched by `storage_selector.lib`, the storage-selector exists and it fails to compile because of mandatory parameter `storage-selector.storage`.

**Comment by marcuschangarm** [comment]
Ah, I understand now. So even if your application is not calling the storage-selector, you can't compile it unless you set a storage device.

If you are not calling the storage-selector when compiling for the board with limited storage, it doesn't really matter what device you set it to, the linker should remove the code anyway.

**Comment by artokin** [comment]
Yes, that is the problem. However, isn't there any other solution? Defining dummy configuration doesn't sound right.

**Comment by marcuschangarm** [comment]
@bridadan your thoughts?

**Comment by bridadan** [comment]
@artokin can you help me understand what those targets are doing to store data if they're not using storage selector? Are they using another method of permanent storage? Or are they completely skipping the storage set?

**Comment by artokin** [comment]
@bridadan , they are completely skipping the storage usage.

**Comment by bridadan** [comment]
@artokin I see. That isn't really a use case we considered when writing this. If the one board is the only using storage, would it be possible to just have a custom block for that one platform instead of using storage-selector? Or is there a particular reason that storage selector is being used in this case?

Alternatively if you really need to use storage-selector, you should be fine using a dummy selection or the selection that your boards with storage. You shouldn't have much of a ROM or RAM penalty if you don't use the APIs in that case.

**Comment by artokin** [comment]
OK, the application will be updated to custom block for the specific platform.
