### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/storage-selector#35]
```
[Warning] SPIFBlockDevice.h@59,0:  #611-D: overloaded virtual function "BlockDevice::get_erase_size"  is only partially overridden in class "SPIFBlockDevice" 
[Warning] DataFlashBlockDevice.h@62,0:  #611-D: overloaded virtual function "BlockDevice::get_erase_size"  is only partially overridden in class "DataFlashBlockDevice" 
[Warning] FlashIAPBlockDevice.h@40,0:  #611-D: overloaded virtual function "BlockDevice::get_erase_size"  is only partially overridden in class "FlashIAPBlockDevice" 
Compile [ 99.9%]: SPIFBlockDevice.cpp
[Warning] SPIFBlockDevice.h@59,0:  #611-D: overloaded virtual function "BlockDevice::get_erase_size"  is only partially overridden in class "SPIFBlockDevice"

```
Compiling mbed-cloud-client-example with Mbed OS 5.9.0 and ARMCC5

**Comment by bridadan** [comment]
Looks to be an issue with the underlying libraries.

Does this fall into your area @geky?

**Comment by geky** [comment]
Ah, @davidsaada, @ARMmbed/mbed-os-storage, FYI.

The `get_erase_size(bd_addr_t)` overload is a specialized overload and optional, since most block devices don't have different erase sizes.

I can't think of a workaround other than just adding the `get_erase_size` overloads to each class. Which is unfortunate.

@teetak01, have you seen this warning on any other compilers? I think it is ARMCC specific. Maybe we should disable this warning since it's likely this pattern is used elsewhere. Thoughts?

**Comment by teetak01** [comment]
@geky same issue comes with IAR7. I would say its valid bug and should be fixed.

**Comment by davidsaada** [comment]
No biggie, will fix it.

**Comment by yossi2le** [comment]
@geky, @davidsaada 
maybe instead of virtual function it is better to have get_erase_size declared in base class with MBED_WEAK so it can be override if we like or use the default if we preferred not to.

**Comment by davidsaada** [comment]
> maybe instead of virtual function it is better to have get_erase_size declared in base class with MBED_WEAK so it can be override if we like or use the default if we preferred not to.

Need to implement the derived functions anyway, as any default implementation in the base class won't fit the inheriting classes.

**Comment by geky** [comment]
> Need to implement the derived functions anyway, as any default implementation in the base class won't fit the inheriting classes.

If the default implementation of `get_erase_size(addr)` calls `get_erase_size()`, won't overriding only `get_erase_size()` provide the implementation for both?

**Comment by davidsaada** [comment]
Fixed in [spif-driver#17](https://github.com/ARMmbed/spif-driver/pull/17), [dataflash-driver#10](https://github.com/ARMmbed/dataflash-driver/pull/10) and [flashiap-driver#2](https://github.com/ARMmbed/flashiap-driver/pull/2).

**Comment by geky** [comment]
Thanks for taking care of this!, @teetak01, shall we close this issue?

**Comment by geky** [comment]
Ah good point

**Comment by geky** [comment]
Here we go
https://github.com/ARMmbed/storage-selector/pull/37
